// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameNftToken = "nft_token"

// NftToken mapped from table <nft_token>
type NftToken struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Name         string `gorm:"column:name" json:"name"`
	ChainID      int64  `gorm:"column:chain_id" json:"chain_id"`
	ChainName    string `gorm:"column:chain_name" json:"chain_name"`
	ChainIcon    string `gorm:"column:chain_icon" json:"chain_icon"`
	Img          string `gorm:"column:img" json:"img"`
	ContractAddr string `gorm:"column:contract_addr" json:"contract_addr"`
	HolderNum    int64  `gorm:"column:holder_num" json:"holder_num"`
	Abi          string `gorm:"column:abi" json:"abi"`
	Btns         string `gorm:"column:btns;comment:对应的按钮" json:"btns"` // 对应的按钮
	DeployAddr   string `gorm:"column:deploy_addr" json:"deploy_addr"`
}

// TableName NftToken's table name
func (*NftToken) TableName() string {
	return TableNameNftToken
}
